# v10 with increased smoothing (eps=0.1)

random_seed: 0

batch_size: 1
num_classes: 2
ftr: 'Street'
n_epoch: 500

train_annot: 'assets/train_sample.txt'
val_annot: 'assets/val_sample.txt'

H: 1024
W: 1024

model: 'unet'

optimizer: 'adam'
lr: 1e-4
weight_decay: 1e-4
adam_eps: 0.1
amsgrad: True

hnm: 2
loss_weights: [1, 1]
# scheduler: 0.98

CHCEKPOINT_DIR: 'checkpoints/'

use_augmentation: False