# From oevrfit street v9 (lr=1e-5)

random_seed: 0

batch_size: 1
num_classes: 2
ftr: 'Street'
n_epoch: 200
# log_every: 100

train_annot: 'assets/train.txt'
val_annot: 'assets/val.txt'

n_segment_layers: 6

optimizer: 'adam'
lr: 1e-5
weight_decay: 1e-4
adam_eps: 0
amsgrad: True

hnm: 2
# loss_weights: [1, 1]
# scheduler: 0.98

CHCEKPOINT_DIR: 'checkpoints/'

vis_batch: 4
metric_batch: 20

use_augmentation: False