# v1 with weight decay : 1e-2

random_seed: 0

batch_size: 1
num_classes: 2
ftr: 'Street'
n_epoch: 500

train_annot: 'assets/train.txt'
val_annot: 'assets/val.txt'

H: 1024
W: 1024

model: 'unet'

optimizer: 'adam'
lr: 1e-4
weight_decay: 1e-2
adam_eps: 0.1
amsgrad: True

hnm: 2
loss_weights: [1, 1]
# scheduler: 0.98

metric_batch: 10
vis_batch: 2

CHCEKPOINT_DIR: 'checkpoints/'

use_augmentation: False