# OF_street_v11

random_seed: 0

batch_size: 1
num_classes: 2
ftr: 'Street'
n_epoch: 500

train_annot: 'assets/train.txt'
val_annot: 'assets/val.txt'

H: 1024
W: 1024

model: 'unet'

optimizer: 'adam'
lr: 1e-5
weight_decay: 1e-4
adam_eps: 0.1
amsgrad: True

hnm: 2
loss_weights: [1, 1]
scheduler: 0.98

metric_batch: 20

CHCEKPOINT_DIR: 'checkpoints/'

use_augmentation: False