# Added dropout on only down blocks
random_seed: 0

batch_size: 1
num_classes: 3
n_epoch: 200

train_annot: 'assets/train_sample.txt'
val_annot: 'assets/val_sample.txt'

n_segment_layers: 6

optimizer: 'adam'
lr: 1e-3
weight_decay: 1e-4
adam_eps: 0
amsgrad: True

loss_weights: [1, 2, 3]

CHCEKPOINT_DIR: 'checkpoints/'

use_augmentation: False